# Generated by Django 3.2.13 on 2025-04-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['user'], name='account_ema_user_id_541506_idx'),
        ),
    ]
