# Generated by Django 3.2.13 on 2025-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_emailaddress_account_ema_user_id_541506_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['email'], name='account_ema_email_6aa522_idx'),
        ),
    ]
